# Generated by Django 3.2.5 on 2021-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_photo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keywords',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
