# Generated by Django 3.2.5 on 2021-07-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_project_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='draft',
        ),
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
