# Generated by Django 3.2.5 on 2021-07-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210720_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
